### PR TITLE
Only restore cursor when hide is used

### PR DESCRIPTION
**Pull request by wooorm**
Related: sindresorhus/log-update#2
Related: sindresorhus/log-update#3

Ping me if there are style violations!

### CODE REVIEW

**Comment by sindresorhus** [comment]
The `onetime` check should be in `restore-cursor`.

**Comment by sindresorhus** [comment]
Just remove Node 0.10 from .travis.yml to make the tests pass.

**Comment by wooorm** [comment]
:+1:

**Comment by wooorm** [comment]
This should do the trick!

**Pull request merged**
